# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-08 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='district',
        ),
        migrations.RemoveField(
            model_name='district',
            name='division',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
